### ISSUE TITLE
Python and CLI function to run CLIP on directory or zip file of images

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/image-tagging-tools#4]
- command line arguments and usage must be documented in readme.md
- should be usable from command line and from python (in colab)

1> Take a .zip file or an directory of images

2> Output a json file to /output/clip-cache

3> Each JSON entry has 
- filename
- filename + path
- file size in bytes
- the BLAKE2 hash of the image (faster than sha256)
-- the BLAKE2 hash is called "file-hash-id". Which is our primary key
- file extension (gif, png, jpg, other)
- the CLIP vector
-- clip vector includes a vector (512 floats) and includes the model; 
-- the clip model is a string like "ViT-B-32'"

https://github.com/kk-digital/open_clip
- usage is in the "Linear-probe evaluation" section

- image_features = model.encode_image(image_input)

4> Have utility that reads all JSON files/clip vectors into memory into a map
- print the JSON file size (MB loaded) and total time in seconds. And MB/S rate for reading the JSON files
- have ability to get the CLIP model + CLIP vector from the BLAKE2 hash
- do one map per CLIP-model?

For #4
- do example in python of loading all the CLIP-cache files into map and using API
- as it will be used by other applications

Question:
- should the clip output files be in /clip-cache/model-name/[json-files]

5>
- Put ./output directory into the .gitignore ignore
- Put ./input directory into .gitignore

----

Example Usage:
input/tagged-images
input/dataset01.zip
input/dataset02.zip
input/validation-images

^^ Run script on each directory individually, producing one file in clip-cache for each
- tagged-images.json
- dataset01.zip.json
- dataset02.zip.json
- validation-images.json

^^ run script on whole folder input
- output input.json to clip-cache

**Comment by Volpe95** [comment]
adding more features/modifications for this ticket to be tracked. 

1- in the json file; if the input is the tagged images folder; then we want to put the tags in the .json file also

2- You may want to have array of vectors like type CLIP, Model, then Vector (because we may have multiple later; not all of them are clip)
  *. Type (clip)
  *. Model (the specific model)
  *. Vector (the data)

3-"name": "M2E1YzYyZjEwMzA2Yjg0MGI2NTFlYTNhMDNkMDQwZmNiYTNlYzQwNDZmYjYwNGU0MGQ2N2RmOWE5ZWYwNDRkZA==.png",
        "type": "PNG",

use

file-name
file-path
file-type

for these field names

4- for GIF you just take the first image in GIF sequence

**Comment by Volpe95** [comment]
Also, add image resolution, x,y
